u_max: 640 #1280
v_max: 480 #720
lambda_: 0.03 #0.01 , 0.005
min_error: 100
max_error: 70000
f_x: 502.3016357421875 #695.9951
f_y: 502.3016357421875  #695.9951 
num_pairs: 24
image_path: 'goalrgb.jpg'
max_velocity: 1.0


# DINO feature detection parameters
dino_input_size: 308
background_thresh: 0.005
thresh_filter_keypoints: 1
use_feature_binning: true  # Add this line

# Sampling parameters
num_samples: 100
num_circles: 4
circle_radius_aug: 0.08

# Convergence parameters
velocity_convergence_threshold: 0.00008
velocity_threshold_translation: 0.0000000000000000005
velocity_threshold_rotation: 0.0000000000000000005
error_threshold_ratio: 0.001
error_threshold_absolute_translation: 0.1
error_threshold_absolute_rotation: 0.1

# Iteration control
min_iterations: 300
max_iterations: 1500

# Velocity history for creating velocity mean
max_velocity_vector_history: 200
ema_alpha: 0.8

